[package]
name = "rocktee"
version = "0.1.0"
authors = ["Rocktee <7312213+rocktee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
